version: 0.2

phases:
  install:
    commands:
      - set -e
      - echo Installing dependencies...
      - python3 -m venv env
      - source env/bin/activate
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'